### ISSUE TITLE
Removal of Trio class

### ISSUE THREAD

**Issue by PMenges** [ghga-de/ghga-metadata-schema#142]
Links between aliases of individuals potentially increase the likelihood of re-identification. This could be particularly problematic for rare diseases (if multiple or all members of a family have the same condition, small number of individuals in a dataset, rare phenotypes etc). Therefore, the Trio class should be deprecated in the non-personal metadata.

The information about pedigree should be captured in a .ped (or a comparable pedigree file) and hanlded similar as the encrypted research data. 
We should indicate that such a file exists in a dataset to highlight that pedigree information is present without showing the family relations in our public non-personal metadata, eG with a separate field has_pedigree for dataset. Data Requesters still can view the .ped files after getting access.

**Comment by mauerk** [comment]
fixed in [#160](https://github.com/ghga-de/ghga-metadata-schema/pull/160)
