### ISSUE TITLE
Model Experiment in a better way

### ISSUE THREAD

**Issue by deepakunni3** [ghga-de/ghga-metadata-schema#2]
Can metadata about an Experiment be better represented/modeled?

**Comment by krausf** [comment]
![Definition of Examination](https://user-images.githubusercontent.com/84305754/122770510-cfa3fe00-d2a5-11eb-98ec-ca1ee7c775b4.jpg)
First brainstorm for "new" modeling of experiment

**Comment by krausf** [comment]
[Draw IO modelling](https://drive.google.com/file/d/1cGE7ELpMWaJJei24bdJpk5TsiEtJ4EMt/view?usp=sharing)
